python run_inference.py \
    --model_name qwen3-vl \
    --model_path Qwen/Qwen3-VL-8B-Instruct \
    --tensor_parallel_size 8 \
    --dataset_type text_qa \
    --dataset_path /fsx-shared/juncheng/dataset/VLM/merge_stage/textual_reasoning_200.jsonl \
    --k 16 \
    --temperature 0.7 \
    --max_new_tokens 1024 \
    --num_samples 5 \
    --save_freq 100 \
    --output_path results/textqa_test_results.jsonl
